# -*- coding: utf-8 -*-
"""04 class

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105q3d_LtCWy8f9KX-99mnZD5nUBuT_0D
"""

#Task 4
def show_palindrome(string):
  new_string=""
  for i in string:
    if i !=" ":
      new_string+=i

  reverse_string = new_string[ : :-1]
  if new_string==reverse_string:
      print("Palindrome")
  else:
      print("Not a palindrome")
inp=input()
show_palindrome(inp)