# -*- coding: utf-8 -*-
"""01 class

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105q3d_LtCWy8f9KX-99mnZD5nUBuT_0D
"""

#Task1
def amikenomota(height,weight):
      height=height/100
      bmi=weight/(height**2)
      bmi=round(bmi,1)
      if bmi<18.5:
        print(f"Score is {bmi}. You are Underweight")
      elif 18.5<=bmi<=24.9:
        print(f"Score is {bmi}. You are Normal")
      elif 25<=bmi<=30:
        print(f"Score is {bmi}. You are Overweight")
      else:
        print(f"Score is {bmi}. You are Obese")
h=int(input("Please give your height in cm: "))
w=int(input("Please give your weight in kg: "))
amikenomota(h,w)