# -*- coding: utf-8 -*-
"""02 [str]

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105q3d_LtCWy8f9KX-99mnZD5nUBuT_0D
"""

#Task2
user_input= input()
word=0
number=0
for i in user_input:
  if ord("A")<=ord(i)<=ord("Z") or ord("a")<=ord(i)<=ord("z"):
    word+=1
  elif chr(48)<=i<=chr(57):
    number+=1
if number==0:
  print("Word")
elif word==0:
  print("Number")
else:
  print("Mixed")