# -*- coding: utf-8 -*-
"""04 [li]

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105q3d_LtCWy8f9KX-99mnZD5nUBuT_0D
"""

#Task4
flag= True
while True:
  p=input()
  if p=="STOP":
    break
  else:
    p=p.split()
  for i in range(len(p)):
    p[i]=int(p[i])
  diff=len(p)-1

  for i in range(len(p)-1):
    if p[i]>p[i+1]:
      d= p[i]-p[i+1]
    else:
      d= p[i+1]-p[i]
    if d>diff:
      flag=False
  if flag:
    print("UB Jumper")
  else:
    print("Not UB Jumper")