# -*- coding: utf-8 -*-
"""04 [str]

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105q3d_LtCWy8f9KX-99mnZD5nUBuT_0D
"""

#Task4
user_input1 = input()
user_input2= input()
common = ''
for i in user_input1:
  if i in user_input2:
    common += i
for i in user_input2:
  if i in user_input1 :
    common+=i
if len(common)==0:
  print("Nothing in common.")
else:
 print(common)