# -*- coding: utf-8 -*-
"""05 home

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105q3d_LtCWy8f9KX-99mnZD5nUBuT_0D
"""

def key_generator(*names):
    encrypted_keys = []
    for name in names:
        first_char = name[0].lower()
        last_char = name[-1].upper()
        middle_chars = name[1:-1]
        middle_chars= middle_chars[ : :-1]
        middle_char=""
        for i in middle_chars:
            middle_char+=(str(ord(i)))
        encrypted_key = first_char + middle_char+ last_char
        encrypted_keys.append(encrypted_key)
    return encrypted_keys
key_list = key_generator("Alex", "Bob", "Trudy")
print("Encrypted Keys:", key_list)